import com.google.gson.Gson;
import com.google.gson.stream.JsonReader;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        System.out.println(getRandomQuoteFromJsonFile());
    }


    public static String getRandomQuoteFromJsonFile() {
        Quote[] quotes  = readQuotesFromJsonfile("resources/recentquotes.json");
        return getRandom(quotes).toString();
        }

    public static Quote getRandom(Quote[] quotes) {
        //return quotes at index [get a random number under 1 * the length of the array]
        return quotes[(int)(Math.random() * quotes.length)];
    }
    public static Quote[] readQuotesFromJsonfile(String filepath) {

        try {
            //create new Gson
            Gson gson = new Gson();
            //Read the json file
            BufferedReader reader = new BufferedReader(new FileReader(filepath));
            //convert the json file to java object (quotes)
            Quote[] quotes = gson.fromJson(reader, Quote[].class);
            return quotes;

        } catch (IOException e) {
            e.printStackTrace();
            return null;
        }
    }
}







