import com.google.gson.Gson;
import com.google.gson.stream.JsonReader;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        QuoteGetter getter = new WebQuoteGetter();
        Quote newQuote = getter.getQuote();
        System.out.print(newQuote);
        addQuote(newQuote);

    }
    public static void addQuote(Quote answer) {
        try {
            //Read the json file
            BufferedReader reader = new BufferedReader(new FileReader("resources/recentquotes2.json"));
            StringBuilder json = new StringBuilder();
            String line = reader.readLine();
            while (line != null) {
                json.append(line);
                line = reader.readLine();
            }
            //create new Gson
            Gson gson = new Gson();
            //fills up quotes[] with json obj converted(using gson) to strings

            Quote[] quotes = gson.fromJson(json.toString(), Quote[].class);

//        change the array length so you can add a new quote
            if (answer.author == "Ron Swanson") {
                quotes = Arrays.copyOf(quotes, quotes.length + 1);

                quotes[quotes.length - 1] = answer;


                Gson gson2 = new Gson();

                String quotes2 = gson2.toJson(quotes, Quote[].class);

                try (FileWriter file = new FileWriter("resources/recentquotes2.json")) {
                    file.write(quotes2);
                    System.out.println("\n" + "Successfully added quote to file.");

                } catch (IOException e) {
                    System.out.println(e);
                }
            }
            }catch (IOException e) {
                System.out.println(e);
            }


    }

}







