/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import java.util.HashSet;
import java.util.Set;

import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testGetRandomQuoteFromJsonFile() {
        String randomTestQuote = App.getRandomQuoteFromJsonFile();

        assertTrue(randomTestQuote.contains("--"));
    }

    @Test
    public void testGetRandomQuote() {
        Quote[] quotes = new Quote[]{new Quote("yay", "mason"), new Quote("hello", "mark")};
        Set<Quote> results = new HashSet<>();
        for (int i = 0; i < 20; i++) {
            results.add(App.getRandom(quotes));
        }
        assertTrue(results.size() > 1);
    }
}
